### PR TITLE
Bugfix #161648933 – Truncate very long gene names

### PR DESCRIPTION
**Pull request by alfonsomunozpomer**
There will come a time when we’ll have tests and Travis reports, but so far this is the heatmap we need, not the heatmap we deserve.

To try it out, test E-GEOD-50777 on `ves-hx-76` in the experiment picker.

### CODE REVIEW

**Comment by monicajianu** [comment]
@alfonsomunozpomer What do you mean by experiment picker in `ves-hx-76`? I'm guessing not this: http://ves-hx-76:8080/gxa/experiments/E-GEOD-50777/Results ?

**Comment by monicajianu** [comment]
It would be nice if we could still see the full (insane) label if we hover over the link. I tried it out and you can achieve this with a `title` attribute and a `useHTML: true` in the `yAxis.labels` config. And if you do this you can get rid of those custom hover events, I think. Unless they serve some mystical purpose I don't quite understand. Besides this... all good!

**Comment by monicajianu** [comment]
Also, I'm wondering if you could use the same approach for the X axis labels... i.e. trim up to a certain number of characters and show full text as a tooltip. And maybe get rid of some of the crazy trigonometry? You could use it for when you tilt the labels, so you don't have to calculate the height of potentially infinitely long labels.
Of course, this improvement is out of scope but I feel compelled to do something about this heatmap code every time I look at it...

**Comment by alfonsomunozpomer** [comment]
Jokes aside, I’d rather leave this for the shiny new implementation of the heatmap, which I hope we’ll tackle over 2019.

**Comment by alfonsomunozpomer** [comment]
@monicajianu Could you please review the latest set of changes and approve/request changes?

**Pull request merged**
